version: "3.9"
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    networks:
      - hackathon_on_rails_network
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD= password
  webpack:
    build: .
    command: ./bin/webpack-dev-server
    volumes:
      - .:/hackathon-on-rails
    ports:
      - '3035:3035'
    environment:
      NODE_ENV: development
      RAILS_ENV: development
      WEBPACKER_DEV_SERVER_HOST: 0.0.0.0
    networks:
      - hackathon_on_rails_network
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/hackathon-on-rails
    ports:
      - "3000:3000"
    networks:
      - hackathon_on_rails_network
    environment:
      RAILS_ENV: development
      WEBPACKER_DEV_SERVER_HOST: webpack
    depends_on:
      - db
      - webpack
networks:
  hackathon_on_rails_network:
    driver: bridge
